### ISSUE TITLE
Integration with Magento 2

### ISSUE THREAD

**Issue by stevewinni** [meebio/omnipay-creditcall#1]
We have been trying to integrate your solution and we have found that we can't reference it within magento as the naming convention is different.... 

loc: vendor/omnipay/common/src/Omnipay/Omnipay.php
in the constructor: \Omnipay\Omnipay $omnipay;

With your plugin;
/vendor/meebio/omnipay-creditcall/src/Gateway.php
We cannot reference it in the constructor due to the hyphen.

Do you have a workaround for this?

**Comment by jan-j** [comment]
I'm not familiar with Magento convention, so I'm not quite sure what the
problem is. Is Magento not using composer or composer autoloading?

**Comment by stevewinni** [comment]
Resolved by, removing updating composer and reinstall. Thanks for the assist....

Are you going to be including the cardCreate functions at any point?

$response = $gateway->createCard(array(
        'card'              => $new_card,
        'customerReference' => $customer_id,
    ))->send();
    if ($response->isSuccessful()) {
       echo "Gateway createCard was successful.\n";
       // Find the card ID
       $card_id = $response->getCardReference();
       echo "Card ID = " . $card_id . "\n";
   }

I will fork in the meantime.....

**Comment by jan-j** [comment]
> Are you going to be including the cardCreate functions at any point?

If you send proper pull request with implementation and tests for it, I will merge it then. Right now I have no interest in developing new features myself.

**Comment by stevewinni** [comment]
Of course no problems....

**Comment by Mudassar-Shaikh** [comment]
@stevewinni , can you just lay down the steps to integrate this framework on magento 2

**Comment by stevewinni-cc** [comment]
Hi @Mudassar-Shaikh very busy at the moment but Ill see what I can do... what is it you need an assistance with? Have you successfully installed with composer yet?

**Comment by Mudassar-Shaikh** [comment]
@stevewinni  I am  building a custom payment module and have to integrate omnipay for my operations. I have tried many examples for doing smae. I need the procedure to integrate omnipay framework with magento 2.

I am using php 7.0.2 and Magento 2.1.7
